# Generated by Django 5.1.7 on 2025-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helikopteri',
            fields=[
                ('h_id', models.IntegerField(db_comment='0', primary_key=True, serialize=False)),
                ('tip', models.CharField(db_comment='1', max_length=20)),
                ('tip_resursa', models.CharField(blank=True, db_comment='2', max_length=5, null=True)),
                ('serijski_broj', models.CharField(db_comment='3', max_length=20)),
                ('reg_oznaka', models.CharField(db_comment='4', max_length=6)),
                ('datum_proizvodnje', models.DateField(blank=True, db_comment='5', null=True)),
                ('broj_oo', models.IntegerField(blank=True, db_comment='6', null=True)),
                ('nalet_do_oo', models.DecimalField(blank=True, db_comment='7', decimal_places=2, max_digits=8, null=True)),
                ('crr_do', models.DecimalField(blank=True, db_comment='8', decimal_places=2, max_digits=8, null=True)),
                ('datum_zadnje_oo', models.DateField(blank=True, db_comment='9', null=True)),
                ('vrr_do', models.DateField(blank=True, db_comment='10', null=True)),
                ('ukupan_nalet', models.PositiveIntegerField(blank=True, db_comment='11', null=True)),
                ('status', models.PositiveIntegerField(blank=True, db_comment='12', null=True)),
                ('gorivo', models.PositiveIntegerField(blank=True, db_comment='13', null=True)),
                ('vrsta', models.CharField(blank=True, db_comment='14', max_length=25, null=True)),
                ('tehnicar', models.CharField(blank=True, db_comment='16', max_length=55, null=True)),
                ('dm', models.CharField(blank=True, db_comment='17. decimalni ili minutni obračun', max_length=1, null=True)),
                ('kv', models.DecimalField(blank=True, db_comment='18. koeficijen vazduha npr 20%vazduha je 0,2', decimal_places=2, max_digits=3, null=True)),
                ('napomena', models.CharField(blank=True, db_comment='19', max_length=300, null=True)),
                ('tip_opsti', models.CharField(blank=True, db_comment='20', max_length=15, null=True)),
                ('ostatak_h', models.DecimalField(blank=True, db_comment='21', decimal_places=2, max_digits=10, null=True)),
                ('ostatak_d', models.DateField(blank=True, db_comment='22', null=True)),
                ('sletanja', models.IntegerField(blank=True, db_comment='23', null=True)),
                ('azurirano', models.DateTimeField(blank=True, db_comment='25', null=True)),
                ('elt_fixni', models.CharField(blank=True, db_comment='26', max_length=15, null=True)),
                ('elt_portable', models.CharField(blank=True, db_comment='27', max_length=15, null=True)),
                ('vazduh', models.PositiveIntegerField(blank=True, db_comment='28', null=True)),
                ('zemlja', models.PositiveIntegerField(blank=True, db_comment='29', null=True)),
                ('transponder_24bit', models.CharField(blank=True, db_comment='30', max_length=255, null=True)),
                ('ostatak_sletanja', models.IntegerField(blank=True, db_comment='31', null=True)),
            ],
            options={
                'db_table': 'helikopteri',
                'db_table_comment': 'Podaci o helikopterima',
                'managed': False,
            },
        ),
    ]
